// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aiigrczdoftqhfrtgpss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpaWdyY3pkb2Z0cWhmcnRncHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTY5OTgsImV4cCI6MjA3MTM3Mjk5OH0.zn543BURF1Yeo0gMZNdz3TDdSkNF0B3MW7ZCF0B4_Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);